# Generated by Django 5.0.6 on 2024-07-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carphoto_carparameter_car_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarParameter',
            new_name='Car',
        ),
    ]
