# Generated by Django 5.0.6 on 2024-07-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_city_car_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='moneycurrency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
