# Generated by Django 5.0.6 on 2024-07-25 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_city_options_alter_moneycurrency_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='ban',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.bantype'),
        ),
    ]
