# Generated by Django 5.0.6 on 2024-07-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_fueltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveWheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_wheel', models.CharField(max_length=64)),
            ],
        ),
    ]
