# Generated by Django 5.0.6 on 2024-07-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_enginetype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EngineType',
            new_name='EngineVolume',
        ),
    ]
