# Generated by Django 5.0.6 on 2024-07-25 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_rename_enginetype_enginevolume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enginevolume',
            options={'verbose_name': 'Engine volume', 'verbose_name_plural': 'Engine volume'},
        ),
    ]
