# Generated by Django 5.0.6 on 2024-07-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_enginevolume_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='horse_power',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
