# Generated by Django 5.0.6 on 2024-07-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_enginevolume_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorsePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_power', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Horse power',
                'verbose_name_plural': 'Horse power',
            },
        ),
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Mileage',
                'verbose_name_plural': 'Mileage',
            },
        ),
    ]
