# Generated by Django 5.0.6 on 2024-07-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_car_horse_power_car_mileage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_unit', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Measure unit',
                'verbose_name_plural': 'Measure unit',
            },
        ),
    ]
