# Generated by Django 5.0.6 on 2024-07-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_measureunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Owner count',
                'verbose_name_plural': 'Owners count',
            },
        ),
    ]
