# Generated by Django 5.0.6 on 2024-07-26 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_car_color_car_drive_wheel_car_engine_volume_car_fuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='place_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.placecount'),
        ),
    ]
