# Generated by Django 5.0.6 on 2024-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_placecount_car_place_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecount',
            name='count',
            field=models.CharField(max_length=2),
        ),
    ]
