# Generated by Django 5.0.6 on 2024-07-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_alter_placecount_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placecount',
            options={'verbose_name': 'Place count', 'verbose_name_plural': 'Places count'},
        ),
    ]
