# Generated by Django 5.0.6 on 2024-07-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0021_marketversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.AlterField(
            model_name='marketversion',
            name='version',
            field=models.CharField(max_length=32),
        ),
    ]
