# Generated by Django 5.0.6 on 2024-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_status_alter_marketversion_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Sale status',
                'verbose_name_plural': 'Sales status',
            },
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='CarСondition',
        ),
        migrations.AlterModelOptions(
            name='carсondition',
            options={'verbose_name': 'Car condition', 'verbose_name_plural': 'Cars conditions'},
        ),
    ]
