# Generated by Django 5.0.6 on 2024-07-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_salestatus_rename_status_carсondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='has_abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_air_conditioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_alloy_wheels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_central_locking_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_hatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_leather_interior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_parking_sensors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_parktronic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_rain_sensor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_rear_view_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_seat_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_seat_ventilation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_side_curtains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='has_xenon',
            field=models.BooleanField(default=False),
        ),
    ]
