# Generated by Django 5.0.6 on 2024-07-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_car_has_abs_car_has_air_conditioner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='has_parking_sensors',
        ),
    ]
