# Generated by Django 5.0.6 on 2024-07-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_remove_car_has_parking_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
